### ISSUE TITLE
Rename failure

### ISSUE THREAD

**Issue by viraptor** [Shopify/bootsnap#107]
I'm running into an issue with the cache file rename when starting parallel cucumber tests.

When starting 32 cucumber processes using https://github.com/grosser/parallel_tests I sometimes (~50% of the time) get an error like:

```
32 processes for 146 features, ~ 4 features per process
No such file or directory @ rb_file_s_rename - (tmp/cache/bootsnap-load-path-cache.96708.tmp, tmp/cache/bootsnap-load-path-cache) (Errno::ENOENT)
```

This happens on bootsnap 1.1.5 on ruby 2.3.3 and is a bit confusing, because the pattern doesn't match the template used for `mktemp` and it's a `rb_file_s_rename`, not `rename` as I'd expect from `bootstrap.c`.

There's no stacktrace, unfortunately.

**Comment by burke** [comment]
Well, [here's where it's happening](https://github.com/Shopify/bootsnap/blob/master/lib/bootsnap/load_path_cache/store.rb#L69-L76). `ENOENT` here would mean either the directory of the target doesn't exist (which is plainly not true because the source is in the same directory), or the source has been removed before we get around to trying to move it.

It *could* be that, if two processes choose the same random number at the same time, one would move the file into place, and the other would just get confused.

With 32 processes, that should only happen 0.49% of the time, and even that is only if they *all* manage to hit that block at precisely the same time -- but maybe the fact that this file actually gets written a number of times is making up for that apparent disparity. I'll revise the code to be more tolerant of this.

**Comment by viraptor** [comment]
It looks like the test system does quite a bit more than just the 32 processes in my case (I see many more renames when `strace`ing) :( I added a stricter guarantee for non-colliding in the new PR.
