### ISSUE TITLE
Question about require and setup

### ISSUE THREAD

**Issue by asaaki** [Shopify/bootsnap#131]
Is there are particular reason, why a potentially simpler approach of

```ruby
gem 'bootsnap', require: 'bootsnap/setup'
```

is not mentioned?
What are the downsides or negative impacts of it? (I couldn't spot any.)
What do I miss, that it cannot be done this way?

**Comment by burke** [comment]
`require 'bundler/setup'` sets up the load path, but the files are not loaded until `Bundler.require` later on. By putting `require 'bootsnap/setup'` immediately after `require 'bundler/setup'`, we minimize the amount of code that must be loaded before activating bootsnap's hooks to speed up code loading.

Your approach works but prevents some portion of gem code from benefiting from the iseq caching provided by bootsnap, since the load order is... I'm not really sure, probably easiest to just model it as 'random'.

**Comment by burke** [comment]
Added a note to the README about this.

**Comment by asaaki** [comment]
Thank you very much, this helped me to understand.
