### ISSUE TITLE
JRuby-compatible implementation for Compile Cache

### ISSUE THREAD

**Issue by burke** [Shopify/bootsnap#164]
I think JRuby supports the necessary features to do compile caching. The C extension bit is really only a performance optimization over some relatively simple ruby code. This is probably less complex than it would seem, especially if we would make the JRuby bit in ruby.

**Comment by headius** [comment]
It should be possible to make the JRuby bits all in Ruby. I'm pulling in @enebo here because he has worked on our persistence stuff a lot more.

There's a couple things we could cache:

* The AST...saves parsing.

There's no existing way in JRuby to serialize an AST, so this needs impl...and might not save very much in the end.

* The compiled "simple" IR (intermediate representation), saves compilation.

This is what we have implemented today. We can dump and load our "simple" IR form. We never saw a great deal of improvement from caching this, but we were testing pretty small apps.

* The compiled "full" IR, saves optimization

This also is not implemented; the full IR has a control-flow graph and more complicated structure that we don't currently persist. Implementation might be a big job.

* The JIT-compiled bytecode, saves JIT

This is a pie-in-the-sky option, but the plumbing is all there and it would cut out almost all of the overhead of loading a file, replacing it with the overhead of verifying bytecode (at JVM level). It could be a good win.

I want to mention also that we have had these mechanisms around for years, but never pushed them forward because the management of stale caches and whatnot seemed complicated. Perhaps you've perfected that end of things, and we can just hook up the right bits now!

**Comment by enebo** [comment]
If we are talking about things not implemented the other route is to kill reification of instrs and operands and walk the persisted format directly.  Most time in IR persistence of our startup (simple) IR is the allocation of those objects.  (note: this may go a bit beyond this library...)  My latest thought has been once our profiler is in place we load to a binary interpreter (walks binary format without as much direct object instantiation.  Once it has been determined to be hot we convert to full IR.  Then potentially JIT later.

The other companion piece to this is that once our profiler is gathering usage then saving the JIT bytecode ends up becoming very attractive so the top few percent of hot methods can just start out JITed.

Unfortunately, for now, this is a bit blue sky.  Leveraging our simple IR persistence we have today would definitely help on reduce startup overhead.  Another feature which helped our IR persistence is lazily decoding instrs for a scope body until it is first called.  So our layer loads all definitions (methods, closures) but until they are first called we just hold off on the final instruction decode.  This is especially effective in saving memory.

**Comment by burke** [comment]
I can't remember right now where we had this discussion, but honestly Shopify doesn't have enough investment in non-MRI engines to spend any effort maintaining code for them. While we'd be open to adding code for JRuby and/or others if someone were willing to volunteer to maintain them a bit, I think https://github.com/Shopify/bootsnap/pull/226 is where we're headed for now.
