### ISSUE TITLE
Is bootsnap telling us to stop monkey-patching gems?

### ISSUE THREAD

**Issue by metalelf0** [Shopify/bootsnap#212]
Hi, I'm facing an issue with `bootsnap v1.3.2` I'm quite confused about.

In a Rails 5.1 app I monkey patched a part of the Devise gem, specifically the `devise/models/trackable.rb` module. I did so by adding a `lib/devise/models/trackable.rb` file with the new logic being redefined in it. This worked as expected.

When I upgraded to Rails 5.2, the monkey-patched file wasn't being loaded anymore, unless I commented out the `require 'bootsnap/setup'` line in `config/boot.rb`.

Is this the intended behaviour? I mean, I've seen quite a lot of Rails apps monkey-patching small parts of gems (or libraries) this way. What's the suggested approach for this? Is there a way to tell bootsnap that some files are present twice in the `$LOAD_PATH` intentionally, so the last one has to be loaded?

Thanks for your great work!

**Comment by burke** [comment]
That's certainly not intentional. The loading behaviour is supposed to be identical, but it doesn't always live up to that aspiration.

If you can reduce this to a trivial application that demonstrates the case we could probably find a solution.]

**Comment by metalelf0** [comment]
@burke , I uploaded a trivial app to https://github.com/metalelf0/devise-and-bootsnap, you can check out the code and see the issue. Let me know if you need any further information. Thanks a lot!

**Comment by metalelf0** [comment]
Hi @burke , do you have any update on this?

Thanks and have a great 2019!

**Comment by burke** [comment]
Ahhhhh I see the problem here:

`devise.rb` registers an autoload for `Devise::Models::Trackable -> devise/models/trackable`, at gem load time, which happens before application initialization.

Without bootsnap, this unresolved path is just registered with ruby's internal autoloader.

With bootsnap, the path is pre-resolved to the path we find in the gem. Later, the application boots and inserts a new path that we would prefer to load the file from.

These are the options I'm aware of:

1. Modify MRI to give us a hook to resolve autoloads at load-time, which is currently handled in C-land;
2. Deal with this failure mode (unable to provide a higher precedence for an autoload target after it has been registered); or
3. Accept the performance hit of completely disabling bootsnap for `autoload` uses.

I'm tempted to continue to prefer 2 but it's not a clear-cut choice.

**Comment by rafaelfranca** [comment]
As maintainer of devise, I really think this way of monking patch a gem, not letting it load the code that it expect to load, is dangerous so I'm more inclined to not support this case on bootsnap.

**Comment by casperisfine** [comment]
> 1. Modify MRI to give us a hook to resolve autoloads at load-time, which is currently handled in C-land;

That was an identified issue back in the bootscale time. Having a proper hook for path resolving would greatly simplify bootsnap and solve many inconsistency issues.

**Comment by burke** [comment]
Ok, while I would like to have that MRI hook, I'm also comfortable with "don't do that" as an answer here as long as we don't. Sorry!
