### ISSUE TITLE
Performance benchmarks in README

### ISSUE THREAD

**Issue by kvirani** [Shopify/bootsnap#24]
The README is a pleasure to read, and quite extensive! 

That said, I was expecting to see some benchmark comparisons (with vs without bootsnap) against one or more large rails apps... OSS ones like [Discourse](https://github.com/discourse/discourse) perhaps?

Can't wait to try out this gem in dev and hopefully eventually (partially) in production. Thanks for the amazing work!

**Comment by wjordan** [comment]
FWIW, I've been seeing a ~50% improvement in boot times, using a file-based caching solution instead of the xattr implementation (see #25). (The xattr implementation may be faster, but it only supports OSX.)

I've been experimenting with booting [`code-dot-org`](https://github.com/code-dot-org/code-dot-org), a large Rails app containing lots of translations within YAML files.

Without caching, the app loads in **~30 seconds**, with caching it loads in **~15 seconds**.

When loading only English locale, the app loads in **~5.7 seconds** without caching **~2.7 seconds**.

**Comment by jules2689** [comment]
- Discourse reports a boot time reduction of approximately 50%, from roughly 6 to 3 seconds on one machine;
- One of our smaller internal apps also sees a reduction of 50%, from 3.6 to 1.8 seconds;
- Our core platform -- a rather large monolithic application -- boots about 75% faster, dropping from around 25s to 6.5s.

I'll add this to the readme

**Comment by jules2689** [comment]
https://github.com/Shopify/bootsnap/commit/d99fa7691586df638c38ade9a42122d321d6360a

Thanks for the suggestion 😄
