### ISSUE TITLE
Gem binstubs add significant amout of time before bootsnap is set up

### ISSUE THREAD

**Issue by vihai** [Shopify/bootsnap#308]
This is more of a documentation thing.

I am using bootsnap to improve load time of system gem executables. Rubygems install a stub that subsequently run the executable in `bin/`. The bin stub activation, however, takes a significant amount of time.

Inserting bootsnap setup in the stub cuts the load time significantly:

```
No bootsnap:
real    0m2,736s
user    0m2,120s
sys     0m0,616s

bootsnap in gem's bin
real    0m1,835s
user    0m1,449s
sys     0m0,387s

bootsnap in stub executable:
real    0m0,678s
user    0m0,562s
sys     0m0,117s
```

It would be nice to be able to place custom code in stub executable but apparently they are hardcoded in rubygems.

**Comment by rafaelfranca** [comment]
Thank you for the suggestion. I agree it would be nice if bundler/Rubygems already included bootsnap optimizations out-of-box. Since at gem installation time we already know where the gems are it would be possible to build the a-bootsnap like cache. We tried this approach years ago on bundler but it was rejected. https://github.com/rubygems/bundler/pull/3882

Maybe you would have a better luck trying this approach on Rubygems?

I'm closing this issues since this is not a problem that we are willing to solve.
