### ISSUE TITLE
Question about: `warning: argument of top-level return is ignored`

### ISSUE THREAD

**Issue by Capncavedan** [Shopify/bootsnap#413]
I get the following warning since updating our project to Ruby 2.7.x from 2.5.x when running tests:

```
/Users/myname/.rvm/gems/ruby-2.7.5@projectname/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39: warning: argument of top-level return is ignored
```

No malfunctions I am aware of, everything works, but curious if there's a recommendation to address it.

This is in our Gemfile:
```
gem "bootsnap", require: false
```

This is the content of our `boot.rb` file:

```ruby
ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../Gemfile', __dir__)

require 'bundler/setup' # Set up gems listed in the Gemfile.
require 'bootsnap/setup' # Speed up boot time by caching expensive operations.
```

### Steps to reproduce
With project using Ruby 2.7.5, Rails 6.0.4.7, parallel_tests 3.8.1, run `bundle exec rake parallel:test`

### Expected behavior
No warning message

### Actual behavior
Warning message

### System configuration

M1 Mac, macOS 12.3.1, RVM
(happened with previous Intel Mac as well)

**Bootsnap version**: 1.11.1

**Ruby version**: 2.7.5

**Rails version**: 6.0.4.7

**Comment by casperisfine** [comment]
@Capncavedan apologies for the delay, I was away all of last week.

So I know the warning is blaming `bootsnap`, but this warning come from either your code or one of your gems.

This happens when you `return something` is at the top level of a file (not in a method).

I'd suggest disabling bootsnap to see where the warning actually points to. Alternatively you can edit bootsnap with `bundle open bootsnap` to print the path being required, which should allow you to locate the file having this issue.

**Comment by Capncavedan** [comment]
Fantastic, thanks for the info @casperisfine.  Much appreciated.
