### ISSUE TITLE
warning: method redefined; discarding old require

### ISSUE THREAD

**Issue by MaxLap** [Shopify/bootsnap#461]
Running a rake test task with verbose set to true, outputs the warning ".../ruby-3.2.2@nagano3/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:8: warning: method redefined; discarding old require"

Here is an example of such a setting
```
  Rake::TestTask.new(:quick_check) do |t|
    # ...
    t.verbose = true
  end
```
Launching a Rails console with `RUBYOPT=-w` also has the same warning.

I guess there could be race conditions if you first `#undef` the method. I wonder if you could turn this into a module that is `#prepend` to `Kernel`?

**Bootsnap version**: 1.17.0

**Ruby version**: 3.2.2

**Rails version**: 7.0.8

**Comment by byroot** [comment]
> I wonder if you could turn this into a module that is `#prepend` to `Kernel`?

No it's not possible because `rubygems` uses a similar alias_method chain, and it doesn't mix well with prepend. Zeitwerk also alias method chain require, so we'd need to coordinate all this which is practically not possible.

In the meantime I can silence that warning using the `alias_method` trick:

```ruby
module Kernel
  module_function

  alias_method :require, :require
  class << self
    alias_method :require, :require
  end

  def require(path)
  end
end
```

It's just weird I never noticed that warning before.

**Comment by MaxLap** [comment]
Understood, thanks for taking the time to explain!
