### ISSUE TITLE
Boot time regression using bootsnap

### ISSUE THREAD

**Issue by sandlerr** [Shopify/bootsnap#51]
Hello,
I'm wondering what instrumentation exists within this gem to help figure out why replacing bootscale with bootsnap caused a regression in my Rails app boot time. The environment is a Ubuntu VM running in Virtualbox on a macos host. The experiment command I've been benchmarking with is `time be rake routes`.

With bootscale, I'm getting times 11-12 seconds.

A cold bootsnap boot took far longer as expected - ~32 seconds.

Subsequent bootsnap runs were 14-15seconds. Turning off iseq caching brought it to parity with bootscale and turning off yaml caching saved another second.

Is it possible to localise if I have some pathological config files or generated iseq that are slowing things down?

If that can be done, I can try to fix and send a PR.

**Comment by burke** [comment]
The only reason I can think off the top of my head is that if you have code coverage enabled, it definitely would be a little slower[1]. Other than that, I'm really not sure what it could be. If you don't have coverage enabled, can you tell me a little more about your setup? Ruby version, bundler version, rails version, platform, kernel version, filesystem, ...

Is your code mounted into the VM using shared folders? If yes, you may be able to fix performance by setting your bootsnap cache_dir to be outside of the shared folder.

[1] coverage and iseq compilation are mutually incompatible. We could optimize this path to be almost-equal but right now there's some overhead because of trying the optimized path each time before raising an exception and walking back out to the slow path.

**Comment by sandlerr** [comment]
Hi @burke,

The code is mounted in via NFS from the macOS host using `config.vm.synced_folder` in a Vagrantfile and these options: `nolock,vers=3,tcp,noatime,actimeo=1`.

Your suggestion about not mounting the cache dir in the NFS partition did the trick! Bootsnap is now a ton faster. I wonder if there are many reads and writes being issued? I don't know if it is possible but maybe the cache could be kept in memory and flushed at once? It could be difficult if there is a one to one mapping from iseq files to ruby files.

Thanks so much for the fix! All I had to do was add a leading `/` to the `cache_dir` from the readme.
